FROM ubuntu:latest

RUN apt update
RUN apt install -y git nodejs npm
WORKDIR /tmp
RUN git clone https://github.com/mpirescarvalho/react-tetris/
WORKDIR /tmp/react-tetris
RUN npm install
RUN npm run build
CMD [ "npm", "start" ]